{{- if .Values.ingress.enabled -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" -}}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "matrix.fullname" . }}
  labels:
    {{- include "matrix.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.hosts.synapse }}
      http:
        paths:
          - path: "/"
            backend:
              service:
                name: "{{ include "matrix.fullname" . }}-synapse"
                port:
                  number: {{ .Values.synapse.service.port }}
            pathType: ImplementationSpecific
    {{- if .Values.element.enabled }}
    - host: {{ .Values.ingress.hosts.element }}
      http:
        paths:
          - path: "/"
            backend:
              service:
                name: "{{ include "matrix.fullname" . }}-element"
                port:
                  number: {{ .Values.element.service.port }}
            pathType: ImplementationSpecific
    {{- end }}
    {{- if .Values.ingress.federation }}
    - host: {{ .Values.ingress.hosts.federation }}
      http:
        paths:
          - path: "/"
            backend:
              service:
                name: "{{ include "matrix.fullname" . }}-synapse-federation"
                port:
                  number: {{ .Values.synapse.service.federation.port }}
            pathType: ImplementationSpecific
    {{- end }}
{{- end }}
